/**
 * PEP 695 GATE — py_type_parameter against FROZEN expectations.
 *
 *     npx tsx src/test/python-oracle/pep695-gate.ts
 *
 * The expectations in EXPECTED_TYPE_PARAMETERS.json came from CPython 3.12's own
 * `ast`, generated by the oracle in ../parser-oracle/python. They are checked in
 * so this repository can validate itself with no interpreter beyond the one the
 * parser already needs — a suite that shells out to a specific CPython build is a
 * suite most machines cannot run.
 *
 * Regenerate from the oracle repo when the fixtures change. Never hand-edit: a
 * hand-written expectation tests only whether its author and the implementer read
 * the spec the same way.
 */
import * as fs from 'fs';
import * as path from 'path';

import { PythonProjectAnalyzer } from '@/workflows/python/python-project-analyzer';

const CORPUS = 'src/test-data/python/verified-py312';
const EXPECTED = path.join(CORPUS, 'EXPECTED_TYPE_PARAMETERS.json');
const OUT = '.pep695-out';

interface Truth {
  owner: string; ownerKind: string; name: string;
  position: number; bound: string; kind: string;
}

function tsv(f: string): Record<string, string>[] {
  const fp = path.join(OUT, f);
  if (!fs.existsSync(fp)) return [];
  const L = fs.readFileSync(fp, 'utf-8').split('\n').filter(Boolean);
  if (!L.length) return [];
  const h = L[0]!.split('\t');
  return L.slice(1).map((l) => {
    const c = l.split('\t');
    return Object.fromEntries(h.map((k, i) => [k, c[i] ?? ''])) as Record<string, string>;
  });
}

export async function runPep695Gate(): Promise<number> {
  fs.rmSync(OUT, { recursive: true, force: true });
  const summary = await new PythonProjectAnalyzer().analyze({
    rootDir: CORPUS, outputDir: OUT, baseMservPath: '/repo',
    serviceVersionLinkHash: 'SERVICE_VERSION_' + '0'.repeat(32),
  });

  const failures: string[] = [];
  if (summary.extractionErrors) failures.push(`${summary.extractionErrors} extraction error(s)`);
  if (summary.filesRejected) failures.push(`${summary.filesRejected} file(s) REJECTED — 3.12 syntax must parse`);

  const want = (JSON.parse(fs.readFileSync(EXPECTED, 'utf-8')) as { rows: Truth[] }).rows;
  const got = tsv('all-python-type-parameters.csv');
  const key = (o: string, n: string, p: string | number) => `${o}|${n}|${p}`;
  const gotMap = new Map(got.map((g) => [key(g['ownerName']!, g['paramName']!, g['position']!), g]));

  let ok = 0;
  for (const w of want) {
    const g = gotMap.get(key(w.owner, w.name, w.position));
    if (!g) { failures.push(`MISSING ${w.owner}[${w.name}] at position ${w.position}`); continue; }
    if ((g['boundText'] ?? '') !== w.bound) {
      failures.push(`${w.owner}[${w.name}] bound: expected ${JSON.stringify(w.bound)}, got ${JSON.stringify(g['boundText'])}`);
      continue;
    }
    if ((g['ownerKind'] ?? '') !== w.ownerKind) {
      failures.push(`${w.owner}[${w.name}] ownerKind: expected ${w.ownerKind}, got ${g['ownerKind']}`);
      continue;
    }
    ok++;
  }
  for (const g of got) {
    const k = key(g['ownerName']!, g['paramName']!, g['position']!);
    if (!want.some((w) => key(w.owner, w.name, w.position) === k)) {
      failures.push(`SPURIOUS ${k} — CPython sees no such parameter`);
    }
  }

  console.log(`PEP 695 gate — ${CORPUS}`);
  console.log(`  expected ${want.length} type parameters; parser emitted ${got.length}`);
  console.log(`  agreeing on name + position + bound + ownerKind: ${ok}/${want.length}`);

  // Tracked, not failed: PythonScopeKind declares TYPE_PARAM, TYPE_ALIAS and
  // TYPE_PARAM_BOUND, and no extractor emits any of them, so §2.20's
  // pyScopeLinkHash points at the enclosing scope rather than the wrapper.
  const pepScopes = tsv('all-python-scopes.csv').filter((s) =>
    ['TYPE_PARAM', 'TYPE_ALIAS', 'TYPE_PARAM_BOUND'].includes(s['scopeKind'] ?? ''));
  if (pepScopes.length === 0) {
    console.log('  KNOWN GAP — PEP 695 scope kinds declared in the enum, emitted by nothing.');
  }

  console.log('');
  if (failures.length) {
    console.log('FAIL');
    for (const f of failures.slice(0, 20)) console.log('  ' + f);
    return 1;
  }
  console.log('PASS  every type parameter matches the frozen CPython 3.12 truth');
  return 0;
}

if (require.main === module) runPep695Gate().then((c) => process.exit(c));
