export const ENTITY_IDENTIFIERS = {
  TYPE_REGISTRY: 'TYPE_REGISTRY',
  SERVICE_VERSION: 'SERVICE_VERSION',
  TYPE_PARAMETER: 'TYPE_PARAMETER',
  TYPE_REFERENCE: 'TYPE_REFERENCE',
  TYPE_ANNOTATION: 'TYPE_ANNOTATION',
  ANNOTATION_ARGUMENT_REFERENCE: 'ANNOTATION_ARGUMENT_REFERENCE',
  METHOD_REGISTRY: 'METHOD_REGISTRY',
  METHOD_PARAMETER: 'METHOD_PARAMETER',
  METHOD_TYPE_PARAMETER: 'METHOD_TYPE_PARAMETER',
  IMPORT_REGISTRY: 'IMPORT_REGISTRY',
  ENUM_CONSTANT: 'ENUM_CONSTANT',
  ENUM_CONSTANT_ARGUMENT_REFERENCE: 'ENUM_CONSTANT_ARGUMENT_REFERENCE',
  FIELD_REGISTRY: 'FIELD_REGISTRY',
  EXPRESSION_REFERENCE: 'EXPRESSION_REFERENCE',
  LOCAL_VARIABLE_REGISTRY: 'LOCAL_VARIABLE_REGISTRY',
  BLOCK_REGISTRY: 'BLOCK_REGISTRY',
  COMMENT_REGISTRY: 'COMMENT_REGISTRY',
  PROPERTY_KEY: 'PROPERTY_KEY',
  PROPERTY_VALUE_SEGMENT: 'PROPERTY_VALUE_SEGMENT',
  SKIPPED_FILE: 'SKIPPED_FILE',
  XML_ELEMENT: 'XML_ELEMENT',
  XML_ATTRIBUTE: 'XML_ATTRIBUTE',
  XML_VALUE_REFERENCE: 'XML_VALUE_REFERENCE',
  YAML_PROPERTY: 'YAML_PROPERTY',
  YAML_VALUE_SEGMENT: 'YAML_VALUE_SEGMENT',
  GRADLE_BLOCK: 'GRADLE_BLOCK',
  GRADLE_DECLARATION: 'GRADLE_DECLARATION',
  GRADLE_VALUE_REFERENCE: 'GRADLE_VALUE_REFERENCE',

  // ---------------------------------------------------------------- Python
  // One prefix per PK. Every child key chains off its parent's hash, so these
  // prefixes also document the FK chain: PY_MODULE is the root, PY_SCOPE is
  // recursive through itself, and PY_CALL_SITE is a pure 1:1 chain off
  // PY_EXPRESSION. Schema v6 section 1.
  PY_MODULE: 'PY_MODULE',
  PY_SCOPE: 'PY_SCOPE',
  PY_BINDING: 'PY_BINDING',
  PY_TYPE: 'PY_TYPE',
  PY_TYPE_BASE: 'PY_TYPE_BASE',
  PY_TYPE_REFERENCE: 'PY_TYPE_REFERENCE',
  PY_METHOD: 'PY_METHOD',
  PY_METHOD_PARAMETER: 'PY_METHOD_PARAMETER',
  PY_FIELD: 'PY_FIELD',
  PY_FIELD_WRITE: 'PY_FIELD_WRITE',
  PY_DECORATOR: 'PY_DECORATOR',
  PY_DECORATOR_ARGUMENT: 'PY_DECORATOR_ARGUMENT',
  PY_IMPORT: 'PY_IMPORT',
  PY_EXPRESSION: 'PY_EXPRESSION',
  PY_CALL_SITE: 'PY_CALL_SITE',
  PY_TYPE_INFERENCE: 'PY_TYPE_INFERENCE',
  PY_COMMENT: 'PY_COMMENT',
  PY_BLOCK: 'PY_BLOCK',
  PY_PARSE_GAP: 'PY_PARSE_GAP',
  PY_TYPE_PARAMETER: 'PY_TYPE_PARAMETER',

  // ------------------------------------------------------------ TypeScript
  // One prefix per PK, and the list doubles as the FK chain: TS_MODULE is the
  // root and every child key chains off its parent's hash (schema section 1),
  // never off a re-derived qualified name. That discipline is not stylistic
  // here — with declaration merging a qualified name collides BY DESIGN
  // (1,986 multi-declaration symbols measured, max 43 for one name).
  TS_MODULE: 'TS_MODULE',
  TS_TYPE: 'TS_TYPE',
  TS_TYPE_HERITAGE: 'TS_TYPE_HERITAGE',
  TS_TYPE_PARAMETER: 'TS_TYPE_PARAMETER',
  TS_TYPE_REFERENCE: 'TS_TYPE_REFERENCE',
  TS_METHOD: 'TS_METHOD',
  TS_METHOD_PARAMETER: 'TS_METHOD_PARAMETER',
  TS_FIELD: 'TS_FIELD',
  TS_FIELD_POSITION: 'TS_FIELD_POSITION',
  TS_ENUM_MEMBER: 'TS_ENUM_MEMBER',
  TS_VARIABLE: 'TS_VARIABLE',
  TS_IMPORT: 'TS_IMPORT',
  TS_EXPORT: 'TS_EXPORT',
  TS_EXPRESSION: 'TS_EXPRESSION',
  /** A pure 1:1 chain off TS_EXPRESSION — a call site IS an expression. */
  TS_CALL_SITE: 'TS_CALL_SITE',
  TS_BLOCK: 'TS_BLOCK',
  TS_COMMENT: 'TS_COMMENT',
  TS_DECORATOR: 'TS_DECORATOR',
  TS_DECORATOR_ARGUMENT: 'TS_DECORATOR_ARGUMENT',
  TS_PARSE_GAP: 'TS_PARSE_GAP',
  TS_TYPE_SATISFIES: 'TS_TYPE_SATISFIES',
  /**
   * Not a fact-relation prefix: the group key is deliberately NOT UNIQUE, so it
   * is never a PK. It gets its own prefix so a group key can never be mistaken
   * for an entity hash in a join.
   */
  TS_DECLARATION_GROUP: 'TS_DECLARATION_GROUP',
} as const;