/**
 * `ts_expression` enums — schema §4.14.
 *
 * Positions 0–24 of the relation are byte-for-byte `java_expression` 0–24, so
 * these enums are deliberately the Java ones plus what TypeScript adds.
 */

/** `ts_expression` c0. */
export enum TsExpressionKind {
  CALL_EXPRESSION = 'CALL_EXPRESSION',
  NEW_EXPRESSION = 'NEW_EXPRESSION',
  PROPERTY_ACCESS = 'PROPERTY_ACCESS',
  ELEMENT_ACCESS = 'ELEMENT_ACCESS',
  IDENTIFIER_REFERENCE = 'IDENTIFIER_REFERENCE',
  THIS_REFERENCE = 'THIS_REFERENCE',
  SUPER_REFERENCE = 'SUPER_REFERENCE',
  LITERAL = 'LITERAL',
  TEMPLATE_EXPRESSION = 'TEMPLATE_EXPRESSION',
  TAGGED_TEMPLATE = 'TAGGED_TEMPLATE',
  ARROW_FUNCTION = 'ARROW_FUNCTION',
  FUNCTION_EXPRESSION = 'FUNCTION_EXPRESSION',
  CLASS_EXPRESSION = 'CLASS_EXPRESSION',
  OBJECT_LITERAL = 'OBJECT_LITERAL',
  ARRAY_LITERAL = 'ARRAY_LITERAL',
  BINARY_EXPRESSION = 'BINARY_EXPRESSION',
  UNARY_EXPRESSION = 'UNARY_EXPRESSION',
  TERNARY_EXPRESSION = 'TERNARY_EXPRESSION',
  ASSIGNMENT_EXPRESSION = 'ASSIGNMENT_EXPRESSION',
  COMPOUND_ASSIGNMENT = 'COMPOUND_ASSIGNMENT',
  AS_EXPRESSION = 'AS_EXPRESSION',
  SATISFIES_EXPRESSION = 'SATISFIES_EXPRESSION',
  TYPE_ASSERTION = 'TYPE_ASSERTION',
  NON_NULL_EXPRESSION = 'NON_NULL_EXPRESSION',
  AWAIT_EXPRESSION = 'AWAIT_EXPRESSION',
  YIELD_EXPRESSION = 'YIELD_EXPRESSION',
  SPREAD_ELEMENT = 'SPREAD_ELEMENT',
  DYNAMIC_IMPORT = 'DYNAMIC_IMPORT',
  /** RESERVED — TSX is out of freeze 1 and this value must carry zero rows. */
  JSX_ELEMENT = 'JSX_ELEMENT',
  /** RESERVED — see above. */
  JSX_SELF_CLOSING = 'JSX_SELF_CLOSING',
  DELETE_TYPEOF_VOID = 'DELETE_TYPEOF_VOID',
  SEQUENCE_EXPRESSION = 'SEQUENCE_EXPRESSION',
}

/** `ts_expression` c1 — the edge from parent to child, and part of the primary key. */
export enum TsEdgeRole {
  ROOT = 'ROOT',
  RECEIVER = 'RECEIVER',
  QUALIFIER = 'QUALIFIER',
  ARGUMENT = 'ARGUMENT',
  METHOD_NAME = 'METHOD_NAME',
  PROPERTY_NAME = 'PROPERTY_NAME',
  INDEX_ARGUMENT = 'INDEX_ARGUMENT',
  LEFT_OPERAND = 'LEFT_OPERAND',
  RIGHT_OPERAND = 'RIGHT_OPERAND',
  TERNARY_CONDITION = 'TERNARY_CONDITION',
  TERNARY_THEN = 'TERNARY_THEN',
  TERNARY_ELSE = 'TERNARY_ELSE',
  UNARY_OPERAND = 'UNARY_OPERAND',
  AS_OPERAND = 'AS_OPERAND',
  SATISFIES_OPERAND = 'SATISFIES_OPERAND',
  SPREAD_OPERAND = 'SPREAD_OPERAND',
  TEMPLATE_SPAN = 'TEMPLATE_SPAN',
  ARROW_BODY = 'ARROW_BODY',
  OBJECT_PROPERTY_VALUE = 'OBJECT_PROPERTY_VALUE',
  ARRAY_ELEMENT = 'ARRAY_ELEMENT',
  TAG_EXPRESSION = 'TAG_EXPRESSION',
  /** RESERVED for TSX. */
  JSX_ATTRIBUTE_VALUE = 'JSX_ATTRIBUTE_VALUE',
  /** RESERVED for TSX. */
  JSX_CHILD = 'JSX_CHILD',
}

/** `ts_expression` c2 — where the ROOT of an expression tree sits. */
export enum TsRootContext {
  EXPRESSION_STATEMENT = 'EXPRESSION_STATEMENT',
  VARIABLE_INITIALIZER = 'VARIABLE_INITIALIZER',
  FIELD_INITIALIZER = 'FIELD_INITIALIZER',
  RETURN_VALUE = 'RETURN_VALUE',
  CONDITION = 'CONDITION',
  ARGUMENT_LIST = 'ARGUMENT_LIST',
  THROW_VALUE = 'THROW_VALUE',
  SWITCH_SUBJECT = 'SWITCH_SUBJECT',
  CASE_LABEL = 'CASE_LABEL',
  LOOP_HEADER = 'LOOP_HEADER',
  PARAMETER_DEFAULT = 'PARAMETER_DEFAULT',
  DECORATOR_EXPRESSION = 'DECORATOR_EXPRESSION',
  EXPORT_VALUE = 'EXPORT_VALUE',
  ENUM_MEMBER_VALUE = 'ENUM_MEMBER_VALUE',
  HERITAGE_EXPRESSION = 'HERITAGE_EXPRESSION',
  ARROW_BODY_EXPRESSION = 'ARROW_BODY_EXPRESSION',
  COMPUTED_PROPERTY_NAME = 'COMPUTED_PROPERTY_NAME',
  YIELD_OR_AWAIT_OPERAND = 'YIELD_OR_AWAIT_OPERAND',
  UNKNOWN_CONTEXT = 'UNKNOWN_CONTEXT',
}

/** `ts_expression` c3 — what c5 points at. */
export enum TsExpressionOwnerKind {
  METHOD = 'METHOD',
  FIELD = 'FIELD',
  VARIABLE = 'VARIABLE',
  BLOCK = 'BLOCK',
  TYPE = 'TYPE',
  MODULE_INIT = 'MODULE_INIT',
  DECORATOR = 'DECORATOR',
  EXPORT = 'EXPORT',
  ENUM_MEMBER = 'ENUM_MEMBER',
  PARAMETER_DEFAULT = 'PARAMETER_DEFAULT',
}

/** `ts_expression` c9. */
export enum TsLiteralType {
  STRING = 'STRING',
  NUMBER = 'NUMBER',
  BIGINT = 'BIGINT',
  BOOLEAN = 'BOOLEAN',
  NULL = 'NULL',
  UNDEFINED = 'UNDEFINED',
  REGEX = 'REGEX',
  TEMPLATE = 'TEMPLATE',
  NO_SUBSTITUTION_TEMPLATE = 'NO_SUBSTITUTION_TEMPLATE',
}

/** `ts_expression` c12. */
export enum TsUnaryFixity {
  PREFIX = 'PREFIX',
  POSTFIX = 'POSTFIX',
}

/**
 * `ts_expression` c14 — what an identifier reference RESOLVED to.
 *
 * The oracle checks c15 against `getSymbolAtLocation`, so `UNKNOWN` here is a
 * measured gap rather than a shrug: it is the number the resolution rate is
 * computed from.
 */
export enum TsReferencedEntityKind {
  TYPE = 'TYPE',
  METHOD = 'METHOD',
  FIELD = 'FIELD',
  VARIABLE = 'VARIABLE',
  PARAMETER = 'PARAMETER',
  ENUM_MEMBER = 'ENUM_MEMBER',
  IMPORT_BINDING = 'IMPORT_BINDING',
  NAMESPACE = 'NAMESPACE',
  THIS = 'THIS',
  SUPER = 'SUPER',
  /** Resolves to something declared outside this analysis — `console`, `Array`, `Promise`. */
  AMBIENT_GLOBAL = 'AMBIENT_GLOBAL',
  UNKNOWN = 'UNKNOWN',
}
