/** `ts_field` enums — schema §4.8. */

/** `ts_field` c11. */
export enum TsFieldAccess {
  PUBLIC_ACCESS = 'PUBLIC_ACCESS',
  PRIVATE_ACCESS = 'PRIVATE_ACCESS',
  PROTECTED_ACCESS = 'PROTECTED_ACCESS',
  /** `#x` — enforced at runtime, unlike `private` which is erased at emit. */
  PRIVATE_NAME_ACCESS = 'PRIVATE_NAME_ACCESS',
  EXPORTED_ACCESS = 'EXPORTED_ACCESS',
  MODULE_LOCAL_ACCESS = 'MODULE_LOCAL_ACCESS',
}

/** `ts_field` c12 — comma-set. */
export enum TsFieldModifier {
  STATIC = 'STATIC',
  READONLY = 'READONLY',
  DECLARE = 'DECLARE',
  ABSTRACT = 'ABSTRACT',
  OVERRIDE = 'OVERRIDE',
  OPTIONAL = 'OPTIONAL',
  DEFINITE_ASSIGNMENT = 'DEFINITE_ASSIGNMENT',
  ACCESSOR = 'ACCESSOR',
}

/** `ts_field` c13. */
export enum TsMemberKind {
  PROPERTY_DECLARATION = 'PROPERTY_DECLARATION',
  PROPERTY_SIGNATURE = 'PROPERTY_SIGNATURE',
  INDEX_SIGNATURE = 'INDEX_SIGNATURE',
  PARAMETER_PROPERTY = 'PARAMETER_PROPERTY',
  OBJECT_LITERAL_PROPERTY = 'OBJECT_LITERAL_PROPERTY',
  AUTO_ACCESSOR = 'AUTO_ACCESSOR',
}
