const out = document.getElementById('out');
document.querySelectorAll('.card > .title').forEach(function (el) {
  el.classList.add('seen', 'x');
  el.classList.toggle(`open`);
  el.classList.replace('a', 'b');
});
const name = 'dyn';
document.querySelector(`#${name}`);
document.querySelector(`.static-tpl`);
out.setAttribute('aria-hidden', 'true');
out.addEventListener('click', () => {});
out.dataset.state = 'on';
out.style.display = 'none';
out.style.setProperty('--gap', '1px');
out.innerHTML = '<span class="badge" id="b1">1</span>';
out.className = 'big red';
out.onclick = null;
document.getElementsByClassName('tab active');
document.createElement('section');
el2.closest('[data-x]');
